[phases.setup]
nixPkgs = ["nodejs-18"]

[phases.install]
cmds = ["rm -rf node_modules package-lock.json", "npm cache clean --force", "npm install --no-cache"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "npm start"